### PR TITLE
Documentation update for toolkit and changes to ml doc structure

### PR DESCRIPTION
**Pull request by cmccarthy1**
* Additional section relating to cross validation
* NLP structure update
* Distribution instructions for FRESH
* Updates to embedPy and JupyterQ docs
* Structural updates for machine learning section

### CODE REVIEW

**Comment by ghost** [comment]
`ml/setup.md`: Can’t follow the section _Docker command_. It has ordered list (1) Install Docker (2) Run… followed by subheading _Install Docker_. Should the items in the ordered list perhaps be as follows?

1. Install Docker
2. Run embedPy
3. Run JupyterQ

The section also has two links _Build instructions for the image_ with respective targets in our embedPy and JupyterQ repos. Can we vary the link texts to distinguish them, e.g. _Build instructions for the embedPy image_?

**Comment by cmccarthy1** [comment]
I've now updated that as a commit, numbering the list caused some issues so I've put them as bullet points (JupyterQ numbering kept reverting to 1. instead of 3.)

**Comment by ghost** [comment]
It’s do-able as an ordered list but the Markdown gets ugly. In my local copy I’ve made the three items subheadings, and amended the link texts as earlier.

**Comment by cmccarthy1** [comment]
Perfect, do I need to make the modifications on my end?

**Comment by ghost** [comment]
No, I don’t think so. I’m making tiny subedits (spelling, punctuation, etc.) throughout and will post results to preview site for you to see before pushing to production.

**Pull request merged**
